### ISSUE TITLE
Todo List의 'Date'

### ISSUE THREAD

**Issue by yijinKim** [ssohyunKim/SWE#1]
Todo List의 'Date'를 지금은 사용자가 입력하는 것으로 계획했는데 'Due'가 마감기한이니까 'Date'는 내가 작성하는 오늘 날짜가 바로 입력되게 하는건 어떨까요??  의견 부탁합니다

**Comment by ssohyunKim** [comment]
자동으로 현재 날짜로 설정되게 한다는 거지요?  좋은 의견입니다.

**Comment by soosan94** [comment]
저는 사용자가 지정할 수 있었으면 좋겠습니다.

**Comment by yijinKim** [comment]
수정에 용이하려면 사용자가 지정하는게 나을 것 같아서 그냥 지금 그대로 가겠습니다.
