### ISSUE TITLE
파일 저장 및 저장 경로

### ISSUE THREAD

**Issue by yijinKim** [ssohyunKim/SWE#2]
입력한 데이터들을 파일로 저장할건가요??
그럼 파일 데이터들을 .txt 파일로 "~\SWE\src"에 넣어놓을까요?
@soosan94  @ssohyunKim

**Comment by ssohyunKim** [comment]
네!

**Comment by soosan94** [comment]
파일 따로 만들어서 관리하는 건 어떨가요?

**Comment by yijinKim** [comment]
> 파일 따로 만들어서 관리하는 건 어떨가요?

어떤 파일?? src안에 contact.txt, todolist.txt, appointment.txt파일만 있는 폴더를 만들자는 말인가요? @soosan94

**Comment by soosan94** [comment]
아 파일이 아니라 폴더! asset 이나 resources 나 폴더 안에 따로 관리하는 게 좋을 것 같아서요

**Comment by yijinKim** [comment]
그럼 Manager를 Asset_Manager로 하면 폴더도 asset이라고 하는게 좋을거같네요.
