### ISSUE TITLE
Manager파일 생성

### ISSUE THREAD

**Issue by ssohyunKim** [ssohyunKim/SWE#3]
Contact_Manager, TodoList_Manager, Appointment_Manager 의 부모클래스인 
Asset_Manager클래스가 정의된 파일이 없는데, 모두에게 필요한 기능이므로 master브랜치에서 상속할 파일을 새로 만드는 것은 어떨까요? @soosan94 @yijinKim

**Comment by soosan94** [comment]
난 Asset_Manager를 상속 받게 해 놓긴 했는데....

**Comment by yijinKim** [comment]
그럼 Manage-> Asset_Manager로 바꿀까요?
그냥 Manager라고 하니까 성격이 불분명한거 같아서요.

**Comment by ssohyunKim** [comment]
> 난 Asset_Manager를 상속 받게 해 놓긴 했는데....

Asset_Manager 클래스가 없는데 그럼 생성해야하지 않을까요?

**Comment by ssohyunKim** [comment]
> 난 Asset_Manager를 상속 받게 해 놓긴 했는데....

Asset_Manager클래스가 정의된 파일이 없는데, 모두에게 필요한 기능이므로 master브랜치에서 상속할 파일을 새로 만드는 것은 어떨까요? @soosan94
