### ISSUE TITLE
메소드 rename

### ISSUE THREAD

**Issue by ssohyunKim** [ssohyunKim/SWE#4]
homeMenu() -> selectHomeMenu()
subMenu() -> selectSubMenu()

동사로 시작하는 함수명으로 select 를 붙여서 바꾸는 건 어떨까요?

**Comment by yijinKim** [comment]
그 subMenu()함수는 그 메뉴부분만 계속 출력해주는거라서 select보다는 showSubMenu()는 어떨까요? @soosan94 @ssohyunKim

**Comment by soosan94** [comment]
전 yijimKim 의견에 동의합니다
