### ISSUE TITLE
Appointment 속성 String[] persons 변수명 관련 이슈

### ISSUE THREAD

**Issue by soosan94** [ssohyunKim/SWE#5]
현재 Appointment 클래스의 속성 하나를 String[] persons 라고 했는데 문법이 틀리긴 했지만 people 보다는 복수라는 것을 한눈에 알 수 있으니 persons가 낫겠죠?

**Comment by yijinKim** [comment]
네!! -s 붙이는게 코드 이해하는데 더 편리할 것 같아요

**Comment by ssohyunKim** [comment]
네! 동의합니다.
