### ISSUE TITLE
todolist 브랜치의 TodoList_Manager.java 에서

### ISSUE THREAD

**Issue by soosan94** [ssohyunKim/SWE#6]
todolist 브랜치의 TodoList_Manager.java 의 create,update,delete 함수에서
일단 임시로` return false` 로 한 건 아는데,
나중에 return을 result 변수로 해주는 게 좋을 까요?
아니면 함수 수행이 성공/실패 했다는 결과를 담는 다른 좋은 변수명이 있을까요?

**Comment by yijinKim** [comment]
isSuccess로 합시다!!!!
