### ISSUE TITLE
파일 저장 및 열기 클래스

### ISSUE THREAD

**Issue by yijinKim** [ssohyunKim/SWE#7]
세 가지 기능 모두 공통적으로 파일을 저장하고 여는 기능을 사용할 것 같아서요.
각자의 클래스에서 구현하는게 좋을까요? 아님 하나의 공통된 클래스에서 구현하는게 좋을까요?

**Comment by soosan94** [comment]
Asset_Manager 클래스에 함수로 구현할까요?

**Comment by yijinKim** [comment]
네 괜찮을거같아요
